package fr.eulbobo.dojo;

import fr.eulbobo.dojo.gameoflife.domain.CellEnvironment;
import fr.eulbobo.dojo.gameoflife.primary.StringCellGenerator;
import fr.eulbobo.dojo.gameoflife.secondary.StringCellDisplay;

public class GameOfLifeApp {

    public static void main(String[] args) throws InterruptedException {
        System.out.println("|----------------|");
        System.out.println("|  Game of Life  |");
        System.out.println("|----------------|");

        CellEnvironment environment = CellEnvironment.builder().from(new StringCellGenerator("""
                .......................................
                .......................................
                .......................................
                .......................................
                ................O..............O.......
                ...............O.O.OOOOOOOOOO.O.O......
                ................O.O..........O.O.......
                .................O...O....O...O........
                ..................O..........O.........
                ...................OOOOOOOOOO..........
                ..................O..........O.........
                ...................OOOOOOOOOO..........
                .......................................
                .......................................
                .......................................
                """)).build();
        StringCellDisplay cellDisplay = new StringCellDisplay();
        do {
            environment.displayTo(cellDisplay);
            cellDisplay.printTo(System.out::println);
            environment.next();
            Thread.sleep(1_000);
            System.out.println("-------------------");
        } while (true);

    }
}